server:
  port: 8000
eureka:
  instance:
    hostname: localhost
    metadata-map:
          user.name: admin
          user.password: admin
          health-check-url-path: /actuator/health
          home-page-url-path: /actuator
          status-page-url-path: /actuator/info
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: kayak-eureka