server:
  port: 8500
spring:
  application:
    name: kayak-system    # 项目名称尽量用小写
  datasource:   
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.211.55.16:3306/cloud?characterEncoding=utf-8&useSSL=false&autoReconnect=true&autoReconnectForPools=true
    username: root
    password: UA78a26wf!
    tomcat:
      max-active: 5
      max-idle: 3
      min-idle: 2
      initial-size: 1  
  jackson:
    serialization:
      #让控制器输出的json字符串格式更美观。
      indent-output: true
  jpa:
    show-sql: true
logging:
  level:
    root: INFO
    org.springframework.web: debug
    org.springframework.jdbc: debug
    com.kayak: trace
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true