spring:
  application:
    name: kayak-system
  datasource:
    url: jdbc:mysql://10.211.55.9:3306/dbname?characterEncoding=utf-8&useSSL=false
    username: 
    password: 
    
server:
  port: 8500
  
eureka:  
  client:
    serviceUrl:  
      defaultZone: http://localhost:8000/eureka/