spring:
  application:
    name: kayak-feigen 
server:
  port: 8700
eureka:  
  client:
    serviceUrl:  
      defaultZone: http://localhost:8000/eureka
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true